import { TVProgram } from '../types';

// Alias dictionary to map all possible URL slugs / casing / variations to the canonical channel ID
export const CHANNEL_ALIASES: Record<string, string> = {
  // Pro TV
  'protv': 'pro-tv',
  'pro_tv': 'pro-tv',
  'pro-tv-hd': 'pro-tv',
  'protvhd': 'pro-tv',
  'pro.tv.hd.ro': 'pro-tv',
  'pro.tv.ro': 'pro-tv',
  'pro-tv-international': 'pro-tv',

  // Antena 1
  'antena1': 'antena-1',
  'antena_1': 'antena-1',
  'antena-1-hd': 'antena-1',
  'antena1hd': 'antena-1',
  'antena.1.hd.ro': 'antena-1',
  'antena.1.ro': 'antena-1',

  // Digi Sport 1
  'digisport1': 'digi-sport-1',
  'digi-sport1': 'digi-sport-1',
  'digisport-1': 'digi-sport-1',
  'digi-sport-1-hd': 'digi-sport-1',
  'digi.sport.1.hd.ro': 'digi-sport-1',
  'digi.sport.1.ro': 'digi-sport-1',

  // Digi Sport 2
  'digisport2': 'digi-sport-2',
  'digi-sport2': 'digi-sport-2',
  'digisport-2': 'digi-sport-2',
  'digi-sport-2-hd': 'digi-sport-2',
  'digi.sport.2.hd.ro': 'digi-sport-2',

  // Digi Sport 3
  'digisport3': 'digi-sport-3',
  'digi-sport3': 'digi-sport-3',
  'digisport-3': 'digi-sport-3',
  'digi-sport-3-hd': 'digi-sport-3',
  'digi.sport.3.hd.ro': 'digi-sport-3',

  // Digi Sport 4
  'digisport4': 'digi-sport-4',
  'digi-sport4': 'digi-sport-4',
  'digisport-4': 'digi-sport-4',
  'digi-sport-4-hd': 'digi-sport-4',
  'digi.sport.4.hd.ro': 'digi-sport-4',

  // Kanal D & D2
  'kanald': 'kanal-d',
  'kanal-d-hd': 'kanal-d',
  'kanal.d.hd.ro': 'kanal-d',
  'kanal.d.ro': 'kanal-d',
  'kanald2': 'kanal-d2',
  'kanal-d-2': 'kanal-d2',
  'kanal.d2.hd.ro': 'kanal-d2',

  // Prima TV & Prima Sport
  'primatv': 'prima-tv',
  'prima-tv-hd': 'prima-tv',
  'prima.tv.hd.ro': 'prima-tv',
  'primasport1': 'prima-sport-1',
  'prima-sport1': 'prima-sport-1',
  'prima.sport.1.hd.ro': 'prima-sport-1',
  'primasport2': 'prima-sport-2',
  'prima.sport.2.hd.ro': 'prima-sport-2',
  'primasport3': 'prima-sport-3',
  'prima.sport.3.hd.ro': 'prima-sport-3',
  'primasport4': 'prima-sport-4',
  'prima.sport.4.hd.ro': 'prima-sport-4',
  'primasport5': 'prima-sport-5',
  'prima.sport.5.hd.ro': 'prima-sport-5',
  'primanews': 'prima-news',
  'prima-news-hd': 'prima-news',
  'prima.news.ro': 'prima-news',

  // Digi24
  'digi-24': 'digi24',
  'digi24-hd': 'digi24',
  'digi-24-hd': 'digi24',
  'digi.24.hd.ro': 'digi24',
  'digi.24.ro': 'digi24',

  // TVR
  'tvr1': 'tvr-1',
  'tvr-1-hd': 'tvr-1',
  'tvr.1.hd.ro': 'tvr-1',
  'tvr.1.ro': 'tvr-1',
  'tvr2': 'tvr-2',
  'tvr-2-hd': 'tvr-2',
  'tvr.2.hd.ro': 'tvr-2',
  'tvrsport': 'tvr-sport',
  'tvr-sport-hd': 'tvr-sport',
  'tvr.sport.hd.ro': 'tvr-sport',
  'tvrinfo': 'tvr-info',
  'tvr-info-hd': 'tvr-info',
  'tvr.info.ro': 'tvr-info',
  'tvrcultural': 'tvr-cultural',
  'tvr.cultural.ro': 'tvr-cultural',
  'tvrfolclor': 'tvr-folclor',
  'tvr.folclor.ro': 'tvr-folclor',
  'tvrinternational': 'tvr-international',
  'tvr.international.ro': 'tvr-international',

  // Pro Arena & Cinema
  'proarena': 'pro-arena',
  'pro-arena-hd': 'pro-arena',
  'pro.arena.hd.ro': 'pro-arena',
  'procinema': 'pro-cinema',
  'pro-cinema-hd': 'pro-cinema',
  'pro.cinema.hd.ro': 'pro-cinema',

  // Antena 3 CNN, Stars, Happy Channel
  'antena3': 'antena-3',
  'antena-3-cnn': 'antena-3',
  'antena3cnn': 'antena-3',
  'antena.3.cnn.hd.ro': 'antena-3',
  'antena.3.ro': 'antena-3',
  'antenastars': 'antena-stars',
  'antena-stars-hd': 'antena-stars',
  'antena.stars.hd.ro': 'antena-stars',
  'antenainternational': 'antena-international',
  'antena.international.ro': 'antena-international',
  'happychannel': 'happy-channel',
  'happy-channel-hd': 'happy-channel',
  'happy.channel.hd.ro': 'happy-channel',
  'acasatv': 'acasa-tv',
  'acasa-tv-hd': 'acasa-tv',
  'acasa.tv.hd.ro': 'acasa-tv',
  'acasagold': 'acasa-gold',
  'acasa.gold.hd.ro': 'acasa-gold',

  // News Channels
  'romaniatv': 'romania-tv',
  'romania-tv-hd': 'romania-tv',
  'romania.tv.ro': 'romania-tv',
  'rtv': 'romania-tv',
  'b1': 'b1-tv',
  'b1tv': 'b1-tv',
  'b1-tv-hd': 'b1-tv',
  'b1.tv.hd.ro': 'b1-tv',
  'realitatea': 'realitatea-plus',
  'realitateatv': 'realitatea-plus',
  'realitatea-plus-hd': 'realitatea-plus',
  'realitatea.plus.ro': 'realitatea-plus',
  'euronews': 'euronews',
  'euronews-romania': 'euronews',
  'euronews.romania.hd.ro': 'euronews',

  // Movies & Series
  'hbo1': 'hbo',
  'hbo-hd': 'hbo',
  'hbo.hd.ro': 'hbo',
  'hbo2': 'hbo-2',
  'hbo-2-hd': 'hbo-2',
  'hbo.2.hd.ro': 'hbo-2',
  'hbo3': 'hbo-3',
  'hbo-3-hd': 'hbo-3',
  'hbo.3.hd.ro': 'hbo-3',
  'cinemaraton': 'cinemaraton',
  'cinemaraton-hd': 'cinemaraton',
  'cinemaraton.ro': 'cinemaraton',
  'cinemax1': 'cinemax',
  'cinemax-hd': 'cinemax',
  'cinemax.hd.ro': 'cinemax',
  'cinemax2': 'cinemax-2',
  'cinemax-2-hd': 'cinemax-2',
  'cinemax.2.hd.ro': 'cinemax-2',
  'filmnow': 'film-now',
  'film-now-hd': 'film-now',
  'film.now.hd.ro': 'film-now',
  'filmcafe': 'filmcafe',
  'film-cafe': 'filmcafe',
  'film.cafe.hd.ro': 'filmcafe',
  'amc-romania': 'amc',
  'amc.ro': 'amc',
  'axn-romania': 'axn',
  'axn.hd.ro': 'axn',
  'diva-universal': 'diva',
  'diva.ro': 'diva',
  'comedycentral': 'comedy-central',
  'comedy.central.ro': 'comedy-central',
  'epicdrama': 'epic-drama',
  'epic.drama.hd.ro': 'epic-drama',

  // Documentaries
  'natgeo': 'national-geographic',
  'nat-geo': 'national-geographic',
  'nationalgeographic': 'national-geographic',
  'national.geographic.hd.ro': 'national-geographic',
  'natgeowild': 'nat-geo-wild',
  'national-geographic-wild': 'nat-geo-wild',
  'national.geographic.wild.hd.ro': 'nat-geo-wild',
  'discovery-channel': 'discovery',
  'discovery.channel.ro': 'discovery',
  'history-channel': 'history',
  'history.channel.hd.ro': 'history',
  'id': 'id-investigation',
  'investigation-discovery': 'id-investigation',
  'id.investigation.discovery.hd.ro': 'id-investigation',
  'animalplanet': 'animal-planet',
  'animal.planet.hd.ro': 'animal-planet',
  'viasatexplore': 'viasat-explore',
  'viasat.explore.hd.ro': 'viasat-explore',
  'viasathistory': 'viasat-history',
  'viasat.history.hd.ro': 'viasat-history',
  'viasatnature': 'viasat-nature',
  'viasat.nature.hd.ro': 'viasat-nature',

  // Kids
  'cartoonnetwork': 'cartoon-network',
  'cartoon.network.ro': 'cartoon-network',
  'disney': 'disney-channel',
  'disneychannel': 'disney-channel',
  'disney.channel.ro': 'disney-channel',
  'disneyjunior': 'disney-junior',
  'disney.junior.ro': 'disney-junior',
  'nick': 'nickelodeon',
  'nickelodeon.ro': 'nickelodeon',
  'nicktoons.ro': 'nicktoons',
  'minimax.ro': 'minimax',

  // Music & Traditions
  'kisstv': 'kiss-tv',
  'kiss.tv.ro': 'kiss-tv',
  'zutv': 'zu-tv',
  'zu.tv.hd.ro': 'zu-tv',
  'utv.ro': 'utv',
  'magictv': 'magic-tv',
  'magic.tv.ro': 'magic-tv',
  'rocktv': 'rock-tv',
  'rock.tv.ro': 'rock-tv',
  'etnotv': 'etno-tv',
  'etno.tv.hd.ro': 'etno-tv',
  'favorittv': 'favorit-tv',
  'favorit.tv.ro': 'favorit-tv',
  'taraftv': 'taraf-tv',
  'taraf.tv.hd.ro': 'taraf-tv',
  'partymix': 'party-mix',
  'party.mix.hd.ro': 'party-mix',
  'trinitastv': 'trinitas-tv',
  'trinitas.tv.hd.ro': 'trinitas-tv',
  'sperantatv': 'speranta-tv',
  'speranta.tv.ro': 'speranta-tv',

  // Sports & Eurosport
  'eurosport1': 'eurosport-1',
  'eurosport-1-hd': 'eurosport-1',
  'eurosport.1.hd.ro': 'eurosport-1',
  'eurosport2': 'eurosport-2',
  'eurosport-2-hd': 'eurosport-2',
  'eurosport.2.hd.ro': 'eurosport-2',

  // National
  'nationaltv': 'national-tv',
  'national.tv.ro': 'national-tv',
  'national24plus': 'national-24-plus',
  'national.24.plus.ro': 'national-24-plus',

  // International News
  'aljazeera': 'al-jazeera',
  'al.jazeera.english.ro': 'al-jazeera',
  'cnn-international': 'cnn',
  'cnn.international.ro': 'cnn',
  'bbc': 'bbc-news',
  'bbcnews': 'bbc-news',
  'bbc.news.ro': 'bbc-news'
};

/**
 * Normalizes any channel ID input (including url slugs, uppercase, dots, underscores, aliases)
 */
export function normalizeChannelId(rawId: string): string {
  if (!rawId) return 'pro-tv';
  const clean = rawId.toLowerCase().trim()
    .replace(/^https?:\/\/[^/]+\/(?:ro\/)?(?:play\/)?/, '')
    .replace(/[^a-z0-9.-]+/g, '-')
    .replace(/(^-|-$)+/g, '');

  if (CHANNEL_ALIASES[clean]) {
    return CHANNEL_ALIASES[clean];
  }

  // Check without dots
  const noDots = clean.replace(/\./g, '-');
  if (CHANNEL_ALIASES[noDots]) {
    return CHANNEL_ALIASES[noDots];
  }

  // Check without hyphens
  const noHyphens = clean.replace(/-/g, '');
  if (CHANNEL_ALIASES[noHyphens]) {
    return CHANNEL_ALIASES[noHyphens];
  }

  return clean;
}

// Complete master list of 75+ Romanian and international TV channels available in the app
export const MASTER_CHANNELS_LIST: TVProgram[] = [
  // --- GENERALIST ---
  {
    id: 'pro-tv',
    title: 'PRO TV HD',
    category: 'Generalist',
    status: 'online',
    quality: '1080p HD',
    rating: 9.6,
    description: 'Pro TV live online direct - Știrile Pro TV, Vocea României, Las Fierbinți, Românii au Talent și divertisment de top în calitate HD.',
    thumbnail: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/pro-tv-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://eb4b8dcf.kablakaka.ru/iptv/3KZ2W9GEEY49ZV/6997/index.m3u8',
    tags: ['protv', 'stiri', 'filme', 'generalist', 'show'],
    views: 18450,
    createdAt: '2026-01-01T00:00:00.000Z',
    isFeatured: true
  },
  {
    id: 'antena-1',
    title: 'Antena 1 HD',
    category: 'Generalist',
    status: 'online',
    quality: '1080p HD',
    rating: 9.3,
    description: 'Antena 1 transmisiune directă online - Observator, Chefi la Cuțite, Super Neatza cu Răzvan și Dani, Asia Express și emisiuni de divertisment.',
    thumbnail: 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/antena-1-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'https://live4dai.antenaplay.ro/live2_sdi14/live2_sdi14_600k.m3u8',
    tags: ['antena1', 'observator', 'chefilacutite', 'generalist'],
    views: 14200,
    createdAt: '2026-01-01T00:00:00.000Z',
    isFeatured: true
  },
  {
    id: 'kanal-d',
    title: 'Kanal D HD',
    category: 'Generalist',
    status: 'online',
    quality: '1080p HD',
    rating: 8.9,
    description: 'Kanal D live online - Știrile Kanal D, Casa Iubirii, Jocul Cuvintelor cu Dan Negru, 40 de Întrebări și cele mai iubite seriale turcești.',
    thumbnail: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/kanal-d-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'https://stream1.kanald.ro/iphone/knd-live.m3u8',
    tags: ['kanald', 'casaiubirii', 'seriale', 'generalist'],
    views: 9800,
    createdAt: '2026-01-01T00:00:00.000Z',
    isFeatured: true
  },
  {
    id: 'kanal-d2',
    title: 'Kanal D2 HD',
    category: 'Generalist',
    status: 'online',
    quality: '1080p HD',
    rating: 8.4,
    description: 'Kanal D2 în direct - Seriale de excepție, filme premiate și transmisiuni exclusive.',
    thumbnail: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/kanal-d2-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'https://stream1.kanald.ro/iphone/knd2-live.m3u8',
    tags: ['kanald2', 'seriale', 'filme'],
    views: 4500,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'prima-tv',
    title: 'Prima TV HD',
    category: 'Generalist',
    status: 'online',
    quality: '1080p HD',
    rating: 8.7,
    description: 'Prima TV live stream online - Starea Nației, Cronica Cârcotașilor, Focus și emisiuni de divertisment de calitate.',
    thumbnail: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/prima-tv-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://eb4b8dcf.kablakaka.ru/iptv/AE8BY6FHF5ZGAG/6995/index.m3u8',
    tags: ['primatv', 'cronicacarcotasilor', 'stareanatiei', 'focus'],
    views: 7600,
    createdAt: '2026-01-01T00:00:00.000Z',
    isFeatured: true
  },
  {
    id: 'tvr-1',
    title: 'TVR 1 HD',
    category: 'Generalist',
    status: 'online',
    quality: '1080p HD',
    rating: 8.5,
    description: 'TVR 1 online direct - Telejurnal, emisiuni culturale, Tezaur Folcloric, Viața Satului și evenimente naționale.',
    thumbnail: 'https://images.unsplash.com/photo-1461151304267-38535e780c79?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/tvr-1-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1461151304267-38535e780c79?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'https://tvr-1.lg.mncdn.com/tvr1/smil:tvr1.smil/playlist.m3u8',
    tags: ['tvr1', 'telejurnal', 'romania', 'cultura'],
    views: 6200,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'tvr-2',
    title: 'TVR 2 HD',
    category: 'Generalist',
    status: 'online',
    quality: '1080p HD',
    rating: 8.3,
    description: 'TVR 2 live - Emisiuni educative, teatru TV, filme europene și talk-show-uri captivante.',
    thumbnail: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/tvr-2-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'https://tvr-2.lg.mncdn.com/tvr2/smil:tvr2.smil/playlist.m3u8',
    tags: ['tvr2', 'cultura', 'teatru', 'generalist'],
    views: 4100,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'tvr-cultural',
    title: 'TVR Cultural',
    category: 'Generalist',
    status: 'online',
    quality: '1080p HD',
    rating: 8.4,
    description: 'TVR Cultural - Postul dedicat artelor, muzicii clasice, literaturii și patrimoniului național.',
    thumbnail: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/tvr-cultural.jpg',
    banner: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'https://tvr-cultural.lg.mncdn.com/tvrcultural/smil:tvrcultural.smil/playlist.m3u8',
    tags: ['tvrcultural', 'arta', 'literatura', 'muzica'],
    views: 3100,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'national-tv',
    title: 'Național TV',
    category: 'Generalist',
    status: 'online',
    quality: '1080p HD',
    rating: 8.1,
    description: 'Național TV live stream - Știri naționale, seriale indiene și emisiuni de divertisment popular.',
    thumbnail: 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/national-tv.jpg',
    banner: 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'https://streamw.m.ro/Aleph/ngrp:Alephbiz.stream_all/playlist.m3u8',
    tags: ['nationaltv', 'stiri', 'seriale'],
    views: 3900,
    createdAt: '2026-01-01T00:00:00.000Z'
  },

  // --- SPORT ---
  {
    id: 'digi-sport-1',
    title: 'Digi Sport 1 HD',
    category: 'Sport',
    status: 'online',
    quality: '1080p HD',
    rating: 9.8,
    description: 'Digi Sport 1 live online direct - Liga 1 Superliga, UEFA Champions League, La Liga, Formula 1 și tenis ATP/WTA.',
    thumbnail: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/digi-sport-1-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://forever.megogo.xyz/iptv/QGB4M3H62GC7E3/2520/index.m3u8',
    tags: ['digisport', 'superliga', 'championsleague', 'fotbal', 'f1'],
    views: 28900,
    createdAt: '2026-01-01T00:00:00.000Z',
    isFeatured: true
  },
  {
    id: 'digi-sport-2',
    title: 'Digi Sport 2 HD',
    category: 'Sport',
    status: 'online',
    quality: '1080p HD',
    rating: 9.4,
    description: 'Digi Sport 2 live stream - Serie A, Ligue 1, handbal Champions League, baschet și sporturi cu motor.',
    thumbnail: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/digi-sport-2-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://forever.megogo.xyz/iptv/QGB4M3H62GC7E3/2522/index.m3u8',
    tags: ['digisport2', 'seriea', 'handbal', 'sport'],
    views: 19400,
    createdAt: '2026-01-01T00:00:00.000Z',
    isFeatured: true
  },
  {
    id: 'digi-sport-3',
    title: 'Digi Sport 3 HD',
    category: 'Sport',
    status: 'online',
    quality: '1080p HD',
    rating: 9.1,
    description: 'Digi Sport 3 live online - Fotbal internațional, turnee de tenis WTA/ATP și meciuri din ligile europene.',
    thumbnail: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/digi-sport-3-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://forever.megogo.xyz/iptv/QGB4M3H62GC7E3/2524/index.m3u8',
    tags: ['digisport3', 'tenis', 'wta', 'sport'],
    views: 12500,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'digi-sport-4',
    title: 'Digi Sport 4 HD',
    category: 'Sport',
    status: 'online',
    quality: '1080p HD',
    rating: 8.9,
    description: 'Digi Sport 4 live stream - Motociclism MotoGP, handbal masculin/feminin și sporturi de contact.',
    thumbnail: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/digi-sport-4-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://forever.megogo.xyz/iptv/QGB4M3H62GC7E3/2526/index.m3u8',
    tags: ['digisport4', 'motogp', 'sport'],
    views: 8900,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'prima-sport-1',
    title: 'Prima Sport 1 HD',
    category: 'Sport',
    status: 'online',
    quality: '1080p HD',
    rating: 9.3,
    description: 'Prima Sport 1 live online - Superliga României, Premier League, UEFA Champions League și studio fotbal.',
    thumbnail: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/prima-sport-1-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://eb4b8dcf.kablakaka.ru/iptv/AE8BY6FHF5ZGAG/6991/index.m3u8',
    tags: ['primasport1', 'premierleague', 'superliga', 'fotbal'],
    views: 15300,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'prima-sport-2',
    title: 'Prima Sport 2 HD',
    category: 'Sport',
    status: 'online',
    quality: '1080p HD',
    rating: 9.0,
    description: 'Prima Sport 2 live stream - La Liga, Bundesliga, baschet NBA și transmisiuni live.',
    thumbnail: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/prima-sport-2-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://eb4b8dcf.kablakaka.ru/iptv/AE8BY6FHF5ZGAG/6992/index.m3u8',
    tags: ['primasport2', 'laliga', 'bundesliga'],
    views: 9400,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'pro-arena',
    title: 'Pro Arena HD',
    category: 'Sport',
    status: 'online',
    quality: '1080p HD',
    rating: 8.9,
    description: 'Pro Arena live stream - UEFA Europa League, sporturi de contact, emisiuni de analiză sportivă și filme de acțiune.',
    thumbnail: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/pro-arena-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://eb4b8dcf.kablakaka.ru/iptv/AE8BY6FHF5ZGAG/6990/index.m3u8',
    tags: ['proarena', 'europaleague', 'sport', 'fight'],
    views: 8900,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'tvr-sport',
    title: 'TVR Sport HD',
    category: 'Sport',
    status: 'online',
    quality: '1080p HD',
    rating: 8.7,
    description: 'TVR Sport - Canalul public al sportului românesc, gimnastică, canotaj, fotbal național și JO.',
    thumbnail: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/tvr-sport-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'https://tvr-sport.lg.mncdn.com/tvrsport/smil:tvrsport.smil/playlist.m3u8',
    tags: ['tvrsport', 'olimpiada', 'romania', 'sport'],
    views: 5700,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'eurosport-1',
    title: 'Eurosport 1 HD',
    category: 'Sport',
    status: 'online',
    quality: '1080p HD',
    rating: 9.4,
    description: 'Eurosport 1 direct online - Turnee de Grand Slam (Australian Open, Roland Garros), ciclism (Turul Franței), sporturi de iarnă.',
    thumbnail: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/eurosport-1-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://forever.megogo.xyz/iptv/QGB4M3H62GC7E3/2530/index.m3u8',
    tags: ['eurosport1', 'tenis', 'ciclism', 'snooker'],
    views: 11400,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'eurosport-2',
    title: 'Eurosport 2 HD',
    category: 'Sport',
    status: 'online',
    quality: '1080p HD',
    rating: 9.2,
    description: 'Eurosport 2 live stream - Sporturi extreme, snooker, atletism și transmisiuni live.',
    thumbnail: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/eurosport-2-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://forever.megogo.xyz/iptv/QGB4M3H62GC7E3/2532/index.m3u8',
    tags: ['eurosport2', 'sport', 'live'],
    views: 7800,
    createdAt: '2026-01-01T00:00:00.000Z'
  },

  // --- ȘTIRI (NEWS) ---
  {
    id: 'digi24',
    title: 'Digi24 HD',
    category: 'Știri',
    status: 'online',
    quality: '1080p HD',
    rating: 9.4,
    description: 'Digi24 live online - Știri de ultimă oră, Jurnalul de Seară cu Cosmin Prelipceanu, analize economice și transmisiuni speciale non-stop.',
    thumbnail: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/digi-24-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'https://edge-ar.rcs-rds.ro/digi24ar/index.m3u8',
    tags: ['digi24', 'stiri', 'breakingnews', 'actualitate'],
    views: 22100,
    createdAt: '2026-01-01T00:00:00.000Z',
    isFeatured: true
  },
  {
    id: 'antena-3',
    title: 'Antena 3 CNN HD',
    category: 'Știri',
    status: 'online',
    quality: '1080p HD',
    rating: 9.1,
    description: 'Antena 3 CNN în direct - Sinteza Zilei cu Mihai Gâdea, Punctul de Întâlnire, În Fata Națiunii și transmisiuni CNN exclusive.',
    thumbnail: 'https://images.unsplash.com/photo-1495020689067-958852a7765e?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/antena-3-cnn-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1495020689067-958852a7765e?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'https://live4dai.antenaplay.ro/live2_sdi15/live2_sdi15_600k.m3u8',
    tags: ['antena3', 'cnn', 'sintezazilei', 'stiri'],
    views: 18700,
    createdAt: '2026-01-01T00:00:00.000Z',
    isFeatured: true
  },
  {
    id: 'romania-tv',
    title: 'România TV',
    category: 'Știri',
    status: 'online',
    quality: '1080p HD',
    rating: 8.8,
    description: 'România TV live - Știri fierbinți, dezbateri politice intense și exclusivități din actualitatea românească.',
    thumbnail: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/romania-tv.jpg',
    banner: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'https://streamw.m.ro/Aleph/ngrp:Alephbiz.stream_all/playlist.m3u8',
    tags: ['romaniatv', 'stiri', 'breakingnews'],
    views: 13200,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'realitatea-plus',
    title: 'Realitatea Plus',
    category: 'Știri',
    status: 'online',
    quality: '1080p HD',
    rating: 8.7,
    description: 'Realitatea Plus live stream - Culisele Statului Paralel, 100% cu Laurențiu Botin și emisiuni de investigație.',
    thumbnail: 'https://images.unsplash.com/photo-1526470608268-f674ce90ebd4?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/realitatea-plus.jpg',
    banner: 'https://images.unsplash.com/photo-1526470608268-f674ce90ebd4?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'https://streamw.m.ro/Aleph/ngrp:Alephbiz.stream_all/playlist.m3u8',
    tags: ['realitatea', 'stiri', 'anchete'],
    views: 9100,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'b1-tv',
    title: 'B1 TV HD',
    category: 'Știri',
    status: 'online',
    quality: '1080p HD',
    rating: 8.5,
    description: 'B1 TV live - Știrile B1, Talk B1, Dosar de Politician și dezbateri obiective despre politica internă.',
    thumbnail: 'https://images.unsplash.com/photo-1495020689067-958852a7765e?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/b1-tv-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1495020689067-958852a7765e?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'https://streamw.m.ro/Aleph/ngrp:Alephbiz.stream_all/playlist.m3u8',
    tags: ['b1tv', 'stiri', 'talkshow'],
    views: 7400,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'euronews',
    title: 'Euronews România HD',
    category: 'Știri',
    status: 'online',
    quality: '1080p HD',
    rating: 8.9,
    description: 'Euronews România - Știri europene verificate, analize de geopolitică și transmisiuni live fără partizanat.',
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/euronews-romania-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'https://streamw.m.ro/Aleph/ngrp:Alephbiz.stream_all/playlist.m3u8',
    tags: ['euronews', 'europa', 'stiri'],
    views: 5300,
    createdAt: '2026-01-01T00:00:00.000Z'
  },

  // --- FILME & SERIALE ---
  {
    id: 'hbo',
    title: 'HBO România HD',
    category: 'Filme',
    status: 'online',
    quality: '1080p HD',
    rating: 9.7,
    description: 'HBO în direct - Filme blockbuster, premiere cinematografice exclusive și cele mai premiate seriale originale HBO.',
    thumbnail: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/hbo-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://forever.megogo.xyz/iptv/QGB4M3H62GC7E3/2550/index.m3u8',
    tags: ['hbo', 'filme', 'seriale', 'blockbuster', 'cinema'],
    views: 24500,
    createdAt: '2026-01-01T00:00:00.000Z',
    isFeatured: true
  },
  {
    id: 'hbo-2',
    title: 'HBO 2 HD',
    category: 'Filme',
    status: 'online',
    quality: '1080p HD',
    rating: 9.3,
    description: 'HBO 2 live - Comedii, filme pentru toată familia, drame emoționante și producții europene.',
    thumbnail: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/hbo-2-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://forever.megogo.xyz/iptv/QGB4M3H62GC7E3/2552/index.m3u8',
    tags: ['hbo2', 'filme', 'comedie'],
    views: 14100,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'hbo-3',
    title: 'HBO 3 HD',
    category: 'Filme',
    status: 'online',
    quality: '1080p HD',
    rating: 9.2,
    description: 'HBO 3 live stream - Maratoane de seriale de top, drame premiate și mini-serii celebre.',
    thumbnail: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/hbo-3-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://forever.megogo.xyz/iptv/QGB4M3H62GC7E3/2554/index.m3u8',
    tags: ['hbo3', 'seriale', 'maraton'],
    views: 11200,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'pro-cinema',
    title: 'Pro Cinema HD',
    category: 'Filme',
    status: 'online',
    quality: '1080p HD',
    rating: 9.2,
    description: 'Pro Cinema live - Filme de acțiune, thrillere, clasice de la Hollywood și producții cinematografice de renume.',
    thumbnail: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/pro-cinema-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://eb4b8dcf.kablakaka.ru/iptv/AE8BY6FHF5ZGAG/6996/index.m3u8',
    tags: ['procinema', 'filme', 'actiune', 'thriller'],
    views: 16800,
    createdAt: '2026-01-01T00:00:00.000Z',
    isFeatured: true
  },
  {
    id: 'cinemaraton',
    title: 'Cinemaraton',
    category: 'Filme',
    status: 'online',
    quality: '1080p HD',
    rating: 9.0,
    description: 'Cinemaraton - Canalul filmului românesc. Cele mai frumoase filme românești clasice și contemporane 24/7.',
    thumbnail: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/cinemaraton.jpg',
    banner: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'https://streamw.m.ro/Aleph/ngrp:Alephbiz.stream_all/playlist.m3u8',
    tags: ['cinemaraton', 'filmeromanesti', 'romania', 'clasic'],
    views: 8900,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cinemax',
    title: 'Cinemax HD',
    category: 'Filme',
    status: 'online',
    quality: '1080p HD',
    rating: 9.1,
    description: 'Cinemax HD live stream - Cinematografie internațională de autor, drame premiate și filme cult.',
    thumbnail: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/cinemax-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://forever.megogo.xyz/iptv/QGB4M3H62GC7E3/2556/index.m3u8',
    tags: ['cinemax', 'filme', 'cult'],
    views: 7900,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'cinemax-2',
    title: 'Cinemax 2 HD',
    category: 'Filme',
    status: 'online',
    quality: '1080p HD',
    rating: 8.9,
    description: 'Cinemax 2 HD - Filme europene de festival, drame psihologice și biografii remarcabile.',
    thumbnail: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/cinemax-2-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://forever.megogo.xyz/iptv/QGB4M3H62GC7E3/2558/index.m3u8',
    tags: ['cinemax2', 'filme', 'festival'],
    views: 5400,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'filmcafe',
    title: 'Film Cafe HD',
    category: 'Filme',
    status: 'online',
    quality: '1080p HD',
    rating: 8.7,
    description: 'Film Cafe live - Filme populare pentru weekend, aventură, mister și comedii savuroase.',
    thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/film-cafe-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://forever.megogo.xyz/iptv/QGB4M3H62GC7E3/2560/index.m3u8',
    tags: ['filmcafe', 'filme', 'aventura'],
    views: 6700,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'axn',
    title: 'AXN HD',
    category: 'Filme',
    status: 'online',
    quality: '1080p HD',
    rating: 9.0,
    description: 'AXN România live - Seriale polițiste de acțiune, NCIS, Criminal Minds, FBI și filme explozive.',
    thumbnail: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/axn-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://forever.megogo.xyz/iptv/QGB4M3H62GC7E3/2562/index.m3u8',
    tags: ['axn', 'politist', 'ncis', 'actiune'],
    views: 11200,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'happy-channel',
    title: 'Happy Channel HD',
    category: 'Filme',
    status: 'online',
    quality: '1080p HD',
    rating: 8.9,
    description: 'Happy Channel live stream - Seriale romantice, telenovele captivante, filme de suflet și emisiuni de stil.',
    thumbnail: 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/happy-channel-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1518895949257-7621c3c786d7?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'https://live4dai.antenaplay.ro/live2_sdi16/live2_sdi16_600k.m3u8',
    tags: ['happychannel', 'seriale', 'romantic', 'telenovele'],
    views: 13900,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'antena-stars',
    title: 'Antena Stars HD',
    category: 'Filme',
    status: 'online',
    quality: '1080p HD',
    rating: 8.7,
    description: 'Antena Stars live - Emisiuni cu vedete din România, mondenități, stil de viață și divertisment non-stop.',
    thumbnail: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/antena-stars-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'https://live4dai.antenaplay.ro/live2_sdi17/live2_sdi17_600k.m3u8',
    tags: ['antenastars', 'vedete', 'monden', 'divertisment'],
    views: 10400,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'acasa-tv',
    title: 'Acasă TV HD',
    category: 'Filme',
    status: 'online',
    quality: '1080p HD',
    rating: 8.8,
    description: 'Acasă TV live direct - Seriale internaționale iubite, producții dramatice și emisiuni de familie.',
    thumbnail: 'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/acasa-tv-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://eb4b8dcf.kablakaka.ru/iptv/AE8BY6FHF5ZGAG/6998/index.m3u8',
    tags: ['acasatv', 'seriale', 'telenovele'],
    views: 9200,
    createdAt: '2026-01-01T00:00:00.000Z'
  },

  // --- DOCUMENTARE ---
  {
    id: 'national-geographic',
    title: 'National Geographic HD',
    category: 'Documentare',
    status: 'online',
    quality: '1080p HD',
    rating: 9.6,
    description: 'National Geographic HD live - Documentare spectaculoase despre știință, explorare, spațiu cosmic și istorie.',
    thumbnail: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/national-geographic-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://forever.megogo.xyz/iptv/QGB4M3H62GC7E3/2570/index.m3u8',
    tags: ['natgeo', 'documentare', 'stiinta', 'natura'],
    views: 17200,
    createdAt: '2026-01-01T00:00:00.000Z',
    isFeatured: true
  },
  {
    id: 'nat-geo-wild',
    title: 'Nat Geo Wild HD',
    category: 'Documentare',
    status: 'online',
    quality: '1080p HD',
    rating: 9.4,
    description: 'Nat Geo Wild - Cele mai impresionante imagini cu viața sălbatică, prădători, oceane și rezervații naturale.',
    thumbnail: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/nat-geo-wild-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://forever.megogo.xyz/iptv/QGB4M3H62GC7E3/2572/index.m3u8',
    tags: ['natgeowild', 'animale', 'natura', 'wildlife'],
    views: 12100,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'discovery',
    title: 'Discovery Channel',
    category: 'Documentare',
    status: 'online',
    quality: '1080p HD',
    rating: 9.5,
    description: 'Discovery Channel live - Inginerie extremă, supraviețuire, MythBusters, Goana după Aur și inovație tehnologică.',
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/discovery-channel.jpg',
    banner: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://forever.megogo.xyz/iptv/QGB4M3H62GC7E3/2574/index.m3u8',
    tags: ['discovery', 'tehnologie', 'supravietuire', 'documentare'],
    views: 15400,
    createdAt: '2026-01-01T00:00:00.000Z',
    isFeatured: true
  },
  {
    id: 'history',
    title: 'History Channel HD',
    category: 'Documentare',
    status: 'online',
    quality: '1080p HD',
    rating: 9.3,
    description: 'History Channel - Secretele istoriei, civilizații antice, războaie mondiale și documentare istorice captivante.',
    thumbnail: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/history-channel-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://forever.megogo.xyz/iptv/QGB4M3H62GC7E3/2576/index.m3u8',
    tags: ['history', 'istorie', 'civilizatii'],
    views: 10800,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'viasat-history',
    title: 'Viasat History HD',
    category: 'Documentare',
    status: 'online',
    quality: '1080p HD',
    rating: 8.9,
    description: 'Viasat History - Producții documentare europene de înaltă ținută despre regate, imperii și evenimente cheie.',
    thumbnail: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/viasat-history-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://forever.megogo.xyz/iptv/QGB4M3H62GC7E3/2578/index.m3u8',
    tags: ['viasathistory', 'istorie', 'documentare'],
    views: 6500,
    createdAt: '2026-01-01T00:00:00.000Z'
  },

  // --- COPII (KIDS) ---
  {
    id: 'cartoon-network',
    title: 'Cartoon Network',
    category: 'Copii',
    status: 'online',
    quality: '1080p HD',
    rating: 9.4,
    description: 'Cartoon Network România - Desene animate populare: Gumball, Teen Titans Go, Craig și Dumbrava, Ben 10 dublate în română.',
    thumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/cartoon-network.jpg',
    banner: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://forever.megogo.xyz/iptv/QGB4M3H62GC7E3/2580/index.m3u8',
    tags: ['cartoonnetwork', 'desene', 'copii', 'animatie'],
    views: 16100,
    createdAt: '2026-01-01T00:00:00.000Z',
    isFeatured: true
  },
  {
    id: 'disney-channel',
    title: 'Disney Channel',
    category: 'Copii',
    status: 'online',
    quality: '1080p HD',
    rating: 9.3,
    description: 'Disney Channel - Seriale Disney pentru adolescenți, animații de top și filme Disney magice.',
    thumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/disney-channel.jpg',
    banner: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://forever.megogo.xyz/iptv/QGB4M3H62GC7E3/2582/index.m3u8',
    tags: ['disneychannel', 'disney', 'copii'],
    views: 14700,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'disney-junior',
    title: 'Disney Junior',
    category: 'Copii',
    status: 'online',
    quality: '1080p HD',
    rating: 9.0,
    description: 'Disney Junior - Clubul lui Mickey Mouse, Spidey, Bluey și desene educative pentru cei mici.',
    thumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/disney-junior.jpg',
    banner: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://forever.megogo.xyz/iptv/QGB4M3H62GC7E3/2584/index.m3u8',
    tags: ['disneyjunior', 'prescolari', 'copii'],
    views: 9800,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'nickelodeon',
    title: 'Nickelodeon HD',
    category: 'Copii',
    status: 'online',
    quality: '1080p HD',
    rating: 9.2,
    description: 'Nickelodeon - SpongeBob Pantaloni Pătrați, Patrula Cățelușilor, Casa Loud și comedii animate.',
    thumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/nickelodeon.jpg',
    banner: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://forever.megogo.xyz/iptv/QGB4M3H62GC7E3/2586/index.m3u8',
    tags: ['nickelodeon', 'spongebob', 'copii'],
    views: 11900,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'minimax',
    title: 'Minimax',
    category: 'Copii',
    status: 'online',
    quality: '1080p HD',
    rating: 8.7,
    description: 'Minimax - Desene animate prietenoase, non-violente, perfecte pentru copii mici și preșcolari.',
    thumbnail: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/minimax.jpg',
    banner: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://forever.megogo.xyz/iptv/QGB4M3H62GC7E3/2588/index.m3u8',
    tags: ['minimax', 'copii', 'desene'],
    views: 7300,
    createdAt: '2026-01-01T00:00:00.000Z'
  },

  // --- MUZICĂ & TRADIȚII ---
  {
    id: 'kiss-tv',
    title: 'Kiss TV',
    category: 'Muzică',
    status: 'online',
    quality: '1080p HD',
    rating: 9.1,
    description: 'Kiss TV live - Cele mai noi hituri românești și internaționale, topuri muzicale și videoclipuri 24/7.',
    thumbnail: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/kiss-tv.jpg',
    banner: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'https://streamw.m.ro/Aleph/ngrp:Alephbiz.stream_all/playlist.m3u8',
    tags: ['kisstv', 'muzica', 'hituri', 'pop'],
    views: 12700,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'zu-tv',
    title: 'ZU TV HD',
    category: 'Muzică',
    status: 'online',
    quality: '1080p HD',
    rating: 9.0,
    description: 'ZU TV - Postul tinerilor, hituri la zi, emisiuni interactive cu DJ Radio ZU și muzică energică.',
    thumbnail: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/zu-tv-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'https://live4dai.antenaplay.ro/live2_sdi18/live2_sdi18_600k.m3u8',
    tags: ['zutv', 'radiozu', 'muzica', 'topuri'],
    views: 10600,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'utv',
    title: 'UTV HD',
    category: 'Muzică',
    status: 'online',
    quality: '1080p HD',
    rating: 8.9,
    description: 'UTV - Muzică urbană, dance, EDM, pop și festivaluri live transmise în format HD.',
    thumbnail: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/utv-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'https://streamw.m.ro/Aleph/ngrp:Alephbiz.stream_all/playlist.m3u8',
    tags: ['utv', 'dance', 'edm', 'muzica'],
    views: 8200,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'etno-tv',
    title: 'Etno TV HD',
    category: 'Muzică',
    status: 'online',
    quality: '1080p HD',
    rating: 8.6,
    description: 'Etno TV - Muzică populară românească, folclor autentic, tradiții și emisiuni de voie bună.',
    thumbnail: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/etno-tv-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'https://streamw.m.ro/Aleph/ngrp:Alephbiz.stream_all/playlist.m3u8',
    tags: ['etnotv', 'folclor', 'muzicapopulara'],
    views: 7900,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'favorit-tv',
    title: 'Favorit TV',
    category: 'Muzică',
    status: 'online',
    quality: '1080p HD',
    rating: 8.4,
    description: 'Favorit TV - Cântece populare de neuitat, interpreți îndrăgiți și datini românești.',
    thumbnail: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/favorit-tv.jpg',
    banner: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'https://streamw.m.ro/Aleph/ngrp:Alephbiz.stream_all/playlist.m3u8',
    tags: ['favorittv', 'folclor', 'muzica'],
    views: 5800,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'taraf-tv',
    title: 'Taraf TV HD',
    category: 'Muzică',
    status: 'online',
    quality: '1080p HD',
    rating: 8.5,
    description: 'Taraf TV - Muzică de petrecere, lăutărească și voie bună non-stop.',
    thumbnail: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/taraf-tv-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'https://streamw.m.ro/Aleph/ngrp:Alephbiz.stream_all/playlist.m3u8',
    tags: ['taraftv', 'petrecere', 'muzica'],
    views: 6400,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'trinitas-tv',
    title: 'Trinitas TV HD',
    category: 'Generalist',
    status: 'online',
    quality: '1080p HD',
    rating: 8.5,
    description: 'Trinitas TV - Televiziunea Patriarhiei Române, transmisiuni religioase, cultură creștină și documentare duhovnicești.',
    thumbnail: 'https://images.unsplash.com/photo-1519817650390-64a93db51149?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/trinitas-tv-hd.jpg',
    banner: 'https://images.unsplash.com/photo-1519817650390-64a93db51149?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'https://streamw.m.ro/Aleph/ngrp:Alephbiz.stream_all/playlist.m3u8',
    tags: ['trinitas', 'biserica', 'ortodox', 'religie'],
    views: 6200,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'speranta-tv',
    title: 'Speranța TV',
    category: 'Generalist',
    status: 'online',
    quality: '1080p HD',
    rating: 8.3,
    description: 'Speranța TV - Emisiuni creștine, viață de familie, sănătate, spiritualitate și educație morală.',
    thumbnail: 'https://images.unsplash.com/photo-1519817650390-64a93db51149?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/speranta-tv.jpg',
    banner: 'https://images.unsplash.com/photo-1519817650390-64a93db51149?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'https://streamw.m.ro/Aleph/ngrp:Alephbiz.stream_all/playlist.m3u8',
    tags: ['sperantatv', 'spiritualitate', 'sanatate'],
    views: 4100,
    createdAt: '2026-01-01T00:00:00.000Z'
  },

  // --- INTERNAȚIONAL ---
  {
    id: 'cnn',
    title: 'CNN International',
    category: 'Știri',
    status: 'online',
    quality: '1080p HD',
    rating: 9.0,
    description: 'CNN International live - Știri globale de ultimă oră, analize politice și transmisiuni din întreaga lume.',
    thumbnail: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/cnn-international.jpg',
    banner: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://forever.megogo.xyz/iptv/QGB4M3H62GC7E3/2590/index.m3u8',
    tags: ['cnn', 'news', 'international'],
    views: 8900,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'bbc-news',
    title: 'BBC News',
    category: 'Știri',
    status: 'online',
    quality: '1080p HD',
    rating: 9.1,
    description: 'BBC News live - Jurnalism de încredere, acoperire internațională completă și reportaje în direct.',
    thumbnail: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/bbc-news.jpg',
    banner: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'http://forever.megogo.xyz/iptv/QGB4M3H62GC7E3/2592/index.m3u8',
    tags: ['bbc', 'news', 'stiri'],
    views: 9400,
    createdAt: '2026-01-01T00:00:00.000Z'
  },
  {
    id: 'al-jazeera',
    title: 'Al Jazeera English',
    category: 'Știri',
    status: 'online',
    quality: '1080p HD',
    rating: 8.6,
    description: 'Al Jazeera English - Transmisiune globală de știri în direct, dezbateri și documentare internaționale.',
    thumbnail: 'https://images.unsplash.com/photo-1495020689067-958852a7765e?w=600&auto=format&fit=crop&q=80',
    logo: 'https://static.cinemagia.ro/img/tv/stations_logo/40/al-jazeera-english.jpg',
    banner: 'https://images.unsplash.com/photo-1495020689067-958852a7765e?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'https://live-hls-web-aje.getaj.net/AJE/04.m3u8',
    tags: ['aljazeera', 'international', 'news'],
    views: 4800,
    createdAt: '2026-01-01T00:00:00.000Z'
  }
];

/**
 * Creates or resolves a reliable fallback channel object dynamically if a new or unlisted channel ID is accessed
 */
export function createDynamicChannelFallback(id: string): TVProgram {
  const normId = normalizeChannelId(id);
  const found = MASTER_CHANNELS_LIST.find(c => c.id === normId || c.id === id);
  if (found) return found;

  const prettyTitle = id
    .replace(/-/g, ' ')
    .replace(/\.ro$/i, '')
    .replace(/\./g, ' ')
    .split(' ')
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');

  let category = 'Generalist';
  const lower = id.toLowerCase();
  if (lower.includes('sport') || lower.includes('fotbal') || lower.includes('liga')) category = 'Sport';
  else if (lower.includes('stiri') || lower.includes('news') || lower.includes('24') || lower.includes('info')) category = 'Știri';
  else if (lower.includes('film') || lower.includes('cinema') || lower.includes('hbo') || lower.includes('axn') || lower.includes('comedy') || lower.includes('drama') || lower.includes('serial')) category = 'Filme';
  else if (lower.includes('geo') || lower.includes('discovery') || lower.includes('history') || lower.includes('doc') || lower.includes('nature') || lower.includes('explore')) category = 'Documentare';
  else if (lower.includes('kid') || lower.includes('cartoon') || lower.includes('disney') || lower.includes('nick') || lower.includes('junior') || lower.includes('minimax')) category = 'Copii';
  else if (lower.includes('music') || lower.includes('muzic') || lower.includes('kiss') || lower.includes('zu') || lower.includes('etno') || lower.includes('taraf') || lower.includes('folk')) category = 'Muzică';

  return {
    id: normId,
    title: prettyTitle,
    category,
    status: 'online',
    quality: '1080p HD',
    rating: 8.8,
    description: `Urmărește postul ${prettyTitle} în direct pe programetv.online gratuit, fără întreruperi, cu ghid EPG actualizat în timp real.`,
    thumbnail: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=600&auto=format&fit=crop&q=80',
    logo: `https://static.cinemagia.ro/img/tv/stations_logo/40/${normId}.jpg`,
    banner: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=1200&auto=format&fit=crop&q=80',
    embedCode: '',
    streamUrl: 'https://live4dai.antenaplay.ro/live2_sdi14/live2_sdi14_600k.m3u8',
    tags: [normId, category.toLowerCase()],
    views: 1200,
    createdAt: new Date().toISOString()
  };
}
