const fs = require('fs');
let content = fs.readFileSync('src/pages/admin/ArticleGenerator.tsx', 'utf8');

const tlds = [
  ['🔥 Unde vedem live', '🔥 Where to watch live'],
  ['Avanpremieră, echipe probabile și ponturi bune', 'Preview, probable lineups and good tips'],
  ['Blockbuster-ul Zilei', 'Match of the Day'],
  ['Spectacolul fotbalistic de pe planetă atinge cote maxime', 'The football spectacle on the planet reaches maximum highs'],
  ['confruntarea epică', 'epic clash'],
  ['se anunță a fi un adevărat roller-coaster de emoții!', 'promises to be a true roller-coaster of emotions!'],
  ['Arena de clasă mondială', 'The world-class arena'],
  ['din orașul gazdă', 'in host city'],
  ['va găzdui un meci crucial', 'will host a crucial match'],
  ['Cuvinte cheie de interes major:', 'High interest keywords:'],
  ['deținători drepturi, stream video gratis fotbal live comentat română, ponturi fotbal gratis', 'broadcasting rights, free live stream video football commentary, free football tips'],
  ['meciuri online gratis, program TV transmisiuni sportive.', 'free online matches, sports broadcast TV schedule.'],
  ['Fanii din ambele țări au creat un decor colorat formidabil în tribune', 'Fans from both countries have created a formidable colorful setup in the stands'],
  ['Obiectivul ambelor formații', 'The goal of both formations'],
  ['Detalii de Ultimă Oră & Echipe de Start', 'Last Minute Details & Starting Lineups'],
  ['Comentatorii noștri sportivi subliniază', 'Our sports commentators emphasize'],
  ['Sistemul tactic ales:', 'Tactical system chosen:'],
  ['Atmosfera pe stadion:', 'Stadium atmosphere:'],
  ['Conectează-te ACUM la Live Stream-ul Video', 'Connect NOW to the Live Video Stream'],
  ['Vrei să fii în alertă cu fiecare pasă', 'Want to stay alert with every pass'],
  ['TELESPECTATOR: INTRĂ LIVE ÎN CADRUL PLAYERULUI', 'VIEWER: ENTER LIVE IN THE PLAYER'],
  ['Momente Tensionate', 'Tense Moments'],
  ['a văzut cartonașul', 'saw the card'],
  ['Tensiuni uriașe în minutul', 'Huge tensions in minute'],
  ['Cartonaș', 'Card'],
  ['încasat de', 'received by'],
  ['Atmosfera s-a încins la maximum', 'The atmosphere heated up to the maximum'],
  ['centralul partidei a fost forțat', 'the main referee was forced'],
  ['Faza a pornit de la un duel extrem de fizic', 'The phase started from an extremely physical duel'],
  ['Intervenția dură a iscat spirite nervoase', 'The harsh intervention sparked nervous spirits'],
  ['Această eliminare definitivă', 'This definitive elimination'],
  ['inferioritate numerică', 'numerical inferiority'],
  ['O lovitură devastatoare pentru antrenor', 'A devastating blow for the coach'],
  ['Deși a scăpat doar cu avertisment', 'Although he escaped only with a warning'],
  ['Urmărește Meciul Live în Direct Online', 'Watch the Match Live Online'],
  ['Fiecare moment suplimentar din meci escaladează intensitatea!', 'Every supplementary moment of the match escalates the intensity!'],
  ['Epic! Meciul', 'Epic! The match'],
  ['s-a încheiat cu scorul spectaculos', 'ended with the spectacular score'],
  ['S-a auzit fluierul de final', 'The final whistle was heard'],
  ['Într-una dintre cele mai complexe și atractive etape', 'In one of the most complex and attractive stages'],
  ['Ambele tabere au dat tot ce aveau mai bun pe teren', 'Both sides gave their best on the pitch'],
  ['Marele merit pentru dinamica acestei partide îi revine', 'The great merit for the dynamics of this match goes to'],
  ['Cu un efort fizic inepuizabil', 'With inexhaustible physical effort'],
  ['Configurația Clasamentului în Grupa', 'Group Standings Configuration'],
  ['Cu acest deznodământ captivant, lupta pentru primele două locuri din clasament devine o adevărată nebunie!', 'With this captivating outcome, the fight for the top two spots in the standings becomes true madness!'],
  ['Vrei să revizionezi cele mai palpitante faze video', 'Do you want to rewatch the most thrilling video phases'],
  ['VEZI REZUMAT VIDEO & CLASAMENT GRUPĂ INTERACTIV', 'SEE VIDEO SUMMARY & INTERACTIVE GROUP STANDINGS'],
  ['cine a câștigat meciul', 'who won the match'],
  ['Redacția Sport Live', 'Sport Live Newsroom'],
  ['Eroare la scrierea articolului', 'Error writing article'],
  ['Se încarcă listele de meciuri', 'Loading match lists'],
  ['Generează instantaneu articole SEO', 'Instantly generate SEO articles'],
  ['Apasă pe butonul de generare', 'Press the generate button'],
  ['Generează Avanpremieră', 'Generate Preview'],
  ['Selectează Confruntarea', 'Select Clash'],
  ['Tip Fază sau Eveniment', 'Phase or Event Type'],
  ['Cartonaș', 'Card'],
  ['Echipa implicată direct', 'Directly involved team'],
  ['Oaspeți', 'Guests'],
  ['Nume Jucător Vizat', 'Targeted Player Name'],
  ['Severitate', 'Severity'],
  ['Galben (Avertisment)', 'Yellow (Warning)'],
  ['roșu', 'red'],
  ['Roșu (Eliminare)', 'Red (Elimination)'],
  ['Scor Final înregistrat', 'Recorded Final Score'],
  ['Detaliu tactici', 'Tactic details'],
  ['Ex: Formație compactă de 4-3-3', 'Ex: Compact 4-3-3 formation'],
  ['Se compune și se stochează articolul...', 'Composing and storing article...'],
  ['Generează și Publică Articol', 'Generate and Publish Article'],
  ['Articolul evenimentului a fost generat și publicat', 'The event article has been successfully generated and published'],
  ['Previzualizare Live în timp real', 'Real-time Live Preview'],
  ['CUPA MONDIALĂ 2026', 'WORLD CUP 2026'],
  ['REPRODUCERE ÎN DIRECT / PROMO', 'LIVE REPRODUCTION / PROMO'],
];

for (const [ro, en] of tlds) {
  content = content.split(ro).join(en);
}

fs.writeFileSync('src/pages/admin/ArticleGenerator.tsx', content);
console.log('Translated Gen Admin');
